export default {
    fontFamily: "'Roboto', 'Helvetica', 'Arial', sans-serif",
    fontSize: 14,
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    useNextVariants: true,
    h1: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 300,
        fontSize: "4rem",
        lineHeight: 1,
        letterSpacing: "-0.01562em",
    },
    h2: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 300,
        fontSize: "3rem",
        lineHeight: 1.3,
        letterSpacing: "-0.00833em",
    },
    h3: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: "2rem",
        lineHeight: 1.04,
        letterSpacing: "0em",
    },
    h4: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: "1.8rem",
        lineHeight: 1.17,
        letterSpacing: "0.00735em",
    },
    h5: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: "1.5rem",
        lineHeight: 1.33,
        letterSpacing: "0em",
    },
    h6: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 500,
        fontSize: "1.25rem",
        lineHeight: 1,
        letterSpacing: "0.0075em",
    },
    subtitle1: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: "1rem",
        lineHeight: 1.75,
        letterSpacing: "0.00938em",
    },
    subtitle2: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 500,
        fontSize: "0.875rem",
        lineHeight: 1.57,
        letterSpacing: "0.00714em",
    },
    body1Next: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: "1rem",
        lineHeight: 1.5,
        letterSpacing: "0.00938em",
    },
    body2Next: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: "0.875rem",
        lineHeight: 1.5,
        letterSpacing: "0.01071em",
    },
    buttonNext: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 500,
        fontSize: "0.875rem",
        lineHeight: 1.75,
        letterSpacing: "0.02857em",
        textTransform: "uppercase",
    },
    captionNext: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: "0.75rem",
        lineHeight: 1.66,
        letterSpacing: "0.03333em"
    },
    overline: {
        color: "rgba(0, 0, 0, 0.87)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: "0.75rem",
        lineHeight: 2.66,
        letterSpacing: "0.08333em",
        textTransform: "uppercase",
    }

}